#pragma once
#include <3ds.h>
#include <sf2d.h>
#include <sfil.h>
#include <sftd.h>
#include <sys/stat.h>
#include <stdio.h>
#include <string.h>
#include <cstdlib>
#include <cstring>
#include <cstdio>
#include <tremor/ivorbiscodec.h>
#include <tremor/ivorbisfile.h>